# Site Settings
name: Data Science for Emergency Services
title: Data Science for Emergency Services
description: The ds4es initiative aims to promote a welcome place for data science projects willing to tackle challenges faced by emergency services.
keywords: "emergency service, EMS, emergency medical services, fire department, firefighting, hazardous materials response, police, law enforcement, criminal investigation, maintenance of public order. markup language, data science, machine learning, artificial intelligence, AI, deep learning, python, open source, FOSS, free and open-source software, collaboration"
email: ds4es.mailbox@gmail.com
# Original 
# disqus_username: "ds'es"
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: https-ds4es-org

show_hero: true
menu:
  - title: Home
    url: /
#  - title: About
#    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml


# Social Media Settings
# Remove the item if you don't need it
github_username: ds4es
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username


# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: false


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-163235556-2"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v0.0.1
